"""
EPUB 생성 모듈 (v2 - 개선 버전)
- 수집된 기사들을 EPUB 전자책으로 변환
- 목차(TOC) 자동 생성 (한글/영문 구분)
- 읽기 시간 추정, 품질 배지, 추출 방법 표시
- 반응형 스타일링
"""

import logging
import math
import os
from datetime import datetime

from ebooklib import epub

from .article_scraper import Article

logger = logging.getLogger(__name__)

# ============================================================
# EPUB 스타일시트 (개선)
# ============================================================
STYLESHEET = """
@charset "UTF-8";

body {
    font-family: "Noto Sans KR", "Malgun Gothic", "Apple SD Gothic Neo",
                 "Segoe UI", "Helvetica Neue", Arial, sans-serif;
    line-height: 1.9;
    margin: 1em 1.2em;
    color: #2d2d2d;
    background-color: #fafafa;
}

/* 헤딩 */
h1 {
    font-size: 1.5em;
    color: #1a1a2e;
    border-bottom: 3px solid #0f3460;
    padding-bottom: 0.4em;
    margin-bottom: 0.3em;
    line-height: 1.4;
}
h2 {
    font-size: 1.2em;
    color: #16213e;
    margin-top: 1.5em;
}

/* 메타 정보 박스 */
.article-meta {
    color: #555;
    font-size: 0.82em;
    margin-bottom: 1.5em;
    padding: 0.7em 0.8em;
    background: linear-gradient(135deg, #f0f4f8 0%, #e8ecf1 100%);
    border-left: 4px solid #0f3460;
    border-radius: 0 4px 4px 0;
}
.article-meta span {
    display: inline-block;
    margin: 0.15em 0;
    margin-right: 1.5em;
}
.article-meta .meta-row {
    display: block;
    margin: 0.2em 0;
}

/* 읽기 시간 배지 */
.reading-time {
    display: inline-block;
    background-color: #0f3460;
    color: white;
    padding: 0.15em 0.6em;
    border-radius: 12px;
    font-size: 0.8em;
    margin-left: 0.5em;
}
.quality-badge {
    display: inline-block;
    padding: 0.1em 0.5em;
    border-radius: 10px;
    font-size: 0.75em;
    font-weight: bold;
    margin-left: 0.3em;
}
.quality-high { background-color: #27ae60; color: white; }
.quality-mid { background-color: #f39c12; color: white; }
.quality-low { background-color: #95a5a6; color: white; }

/* 본문 */
.article-content {
    text-align: justify;
    font-size: 1em;
}
.article-content p {
    margin: 0.7em 0;
    text-indent: 0;
}
.article-content img {
    max-width: 100%;
    height: auto;
    margin: 0.5em 0;
}

/* 원문 링크 */
.source-link {
    margin-top: 2em;
    padding: 0.8em;
    border-top: 2px solid #e0e0e0;
    font-size: 0.82em;
    color: #0f3460;
    background-color: #f8f9fa;
    border-radius: 0 0 4px 4px;
}
.source-link a { color: #0f3460; text-decoration: underline; }

/* 중요도 배지 */
.importance-badge {
    display: inline-block;
    padding: 0.15em 0.7em;
    border-radius: 12px;
    font-size: 0.8em;
    font-weight: bold;
    margin-left: 0.3em;
}
.importance-high { background-color: #e74c3c; color: white; }
.importance-medium { background-color: #f39c12; color: white; }
.importance-low { background-color: #95a5a6; color: white; }

/* 뉴스 날짜 */
.news-date-badge {
    display: inline-block;
    background-color: #2c3e50;
    color: white;
    padding: 0.15em 0.6em;
    border-radius: 12px;
    font-size: 0.8em;
    margin-right: 0.5em;
}

/* 날짜 섹션 구분 */
.date-section-header {
    background: linear-gradient(135deg, #0f3460 0%, #16213e 100%);
    color: white;
    padding: 0.6em 1em;
    border-radius: 6px;
    margin: 1.5em 0 0.5em 0;
    font-size: 1.1em;
}

/* 기사 구분선 */
.article-separator {
    border: none;
    border-top: 1px dashed #ccc;
    margin: 2em 0;
}

/* 커버 */
.cover-title {
    text-align: center;
    margin-top: 25%;
}
.cover-title h1 {
    font-size: 2.2em;
    border: none;
    color: #0f3460;
    margin-bottom: 0.3em;
}
.cover-title .subtitle {
    color: #555;
    font-size: 1.1em;
    margin-bottom: 2em;
}
.cover-title .date {
    font-size: 0.95em;
    color: #888;
}
.cover-title .stats {
    font-size: 0.85em;
    color: #aaa;
    margin-top: 0.5em;
}
.cover-title .powered-by {
    margin-top: 3em;
    font-size: 0.75em;
    color: #bbb;
}

/* TOC 개선 */
nav#toc ol {
    padding-left: 1.5em;
}
nav#toc li {
    margin: 0.4em 0;
}
"""


# ============================================================
# HTML 템플릿
# ============================================================

COVER_HTML = """
<div class="cover-title">
    <h1>{title}</h1>
    <p class="subtitle">{subtitle}</p>
    <p class="date">{date}</p>
    <p class="stats">Total {count} articles (KO: {ko} / EN: {en})</p>
    <p class="stats">Approx. reading time: {total_reading_min} min</p>
    <p class="powered-by">Generated by News Scraper EPUB Agent v2<br/>
    trafilatura + readability-lxml + BeautifulSoup</p>
</div>
"""

ARTICLE_HTML = """
<h1>{title}</h1>
<div class="article-meta">
    <span class="meta-row">
        <span class="news-date-badge">{news_date}</span>
        {importance_badge}
        <span class="reading-time">{reading_min} min read</span>
        {quality_badge}
    </span>
    <span class="meta-row">
        <strong>Source:</strong> {source} &nbsp;|&nbsp;
        <strong>Author:</strong> {author} &nbsp;|&nbsp;
        <strong>Lang:</strong> {language}
    </span>
    <span class="meta-row" style="font-size:0.9em; color:#888;">
        Extracted via: {extraction_method} &nbsp;|&nbsp; {word_count:,} chars
    </span>
</div>
<div class="article-content">
{content}
</div>
<div class="source-link">
    Original: <a href="{url}">{url_short}</a>
</div>
"""


# ============================================================
# 유틸리티
# ============================================================

def _estimate_reading_minutes(text: str, lang: str = "ko") -> int:
    """읽기 시간 추정 (분)"""
    if lang == "ko":
        chars_per_min = 500  # 한글: 분당 ~500자
        return max(1, math.ceil(len(text) / chars_per_min))
    else:
        words = len(text.split())
        wpm = 230  # 영어: 분당 ~230단어
        return max(1, math.ceil(words / wpm))


def _importance_badge_html(importance: str) -> str:
    """중요도에 따른 배지 HTML"""
    imp = importance.upper() if importance else "LOW"
    if imp == "HIGH":
        return '<span class="importance-badge importance-high">HIGH</span>'
    elif imp == "MEDIUM":
        return '<span class="importance-badge importance-medium">MEDIUM</span>'
    return '<span class="importance-badge importance-low">LOW</span>'


def _quality_badge_html(score: float) -> str:
    """품질 점수에 따른 배지 HTML"""
    if score >= 0.5:
        return '<span class="quality-badge quality-high">HIGH</span>'
    elif score >= 0.3:
        return '<span class="quality-badge quality-mid">MID</span>'
    return '<span class="quality-badge quality-low">LOW</span>'


def _format_article_content(article: Article) -> str:
    """기사 내용을 HTML로 포맷팅 (XSS 안전)"""
    if article.html_content:
        return article.html_content

    paragraphs = article.content.split("\n")
    html_parts = []
    for p in paragraphs:
        p = p.strip()
        if p:
            # 기본 HTML 이스케이프
            p = p.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            html_parts.append(f"<p>{p}</p>")
    return "\n".join(html_parts)


def _shorten_url(url: str, max_len: int = 60) -> str:
    """URL 표시용 축약"""
    if len(url) <= max_len:
        return url
    return url[:max_len - 3] + "..."


# ============================================================
# EPUB 빌드
# ============================================================

def build_epub(
    articles: list[Article],
    output_dir: str = "output",
    title: str = None,
) -> str:
    """
    기사 목록을 EPUB 파일로 생성 (v2)

    Args:
        articles: Article 객체 리스트
        output_dir: 출력 디렉토리
        title: EPUB 제목

    Returns:
        생성된 EPUB 파일 경로
    """
    today = datetime.now().strftime("%Y-%m-%d")
    if not title:
        title = "AI & Tech News Digest"

    book = epub.EpubBook()

    # 메타데이터
    book.set_identifier(f"news-digest-{today}")
    book.set_title(title)
    book.set_language("ko")
    book.add_author("News Scraper Agent v2")
    book.add_metadata("DC", "date", today)
    book.add_metadata("DC", "description",
                      f"AI/Tech news {len(articles)} articles ({today})")
    book.add_metadata("DC", "subject", "AI, Technology, News")

    # 스타일시트
    style = epub.EpubItem(
        uid="style",
        file_name="style/default.css",
        media_type="text/css",
        content=STYLESHEET.encode("utf-8"),
    )
    book.add_item(style)

    # 통계 계산
    ko_count = sum(1 for a in articles if a.language == "ko")
    en_count = sum(1 for a in articles if a.language == "en")
    total_reading = sum(
        _estimate_reading_minutes(a.content, a.language) for a in articles
    )

    # 커버 페이지
    cover_html = COVER_HTML.format(
        title=title,
        subtitle="Daily AI / Technology News Collection",
        date=today,
        count=len(articles),
        ko=ko_count,
        en=en_count,
        total_reading_min=total_reading,
    )
    cover_chapter = epub.EpubHtml(
        title="Cover",
        file_name="cover.xhtml",
        lang="ko",
        content=f'<html><head><link rel="stylesheet" href="style/default.css"/></head><body>{cover_html}</body></html>',
    )
    cover_chapter.add_item(style)
    book.add_item(cover_chapter)

    # 기사 챕터 생성
    chapters = []
    ko_chapters = []
    en_chapters = []

    for i, article in enumerate(articles, 1):
        content_html = _format_article_content(article)
        lang_label = "Korean" if article.language == "ko" else "English"
        reading_min = _estimate_reading_minutes(article.content, article.language)

        news_date = getattr(article, "news_date", "") or article.published or "N/A"
        importance = getattr(article, "importance", "") or ""

        article_html = ARTICLE_HTML.format(
            title=article.title,
            source=article.source,
            author=article.author or "N/A",
            published=article.published or "N/A",
            language=lang_label,
            content=content_html,
            url=article.url,
            url_short=_shorten_url(article.url),
            reading_min=reading_min,
            quality_badge=_quality_badge_html(article.quality_score),
            importance_badge=_importance_badge_html(importance),
            news_date=news_date,
            extraction_method=article.extraction_method or "unknown",
            word_count=article.word_count or len(article.content),
        )

        chapter = epub.EpubHtml(
            title=article.title,
            file_name=f"article_{i:02d}.xhtml",
            lang="ko" if article.language == "ko" else "en",
            content=f'<html><head><link rel="stylesheet" href="style/default.css"/></head><body>{article_html}</body></html>',
        )
        chapter.add_item(style)
        book.add_item(chapter)
        chapters.append(chapter)

        if article.language == "ko":
            ko_chapters.append(chapter)
        else:
            en_chapters.append(chapter)

    # 목차 (한글/영문 구분)
    toc = []
    if ko_chapters:
        toc.append((epub.Section("Korean Articles"), ko_chapters))
    if en_chapters:
        toc.append((epub.Section("English Articles"), en_chapters))
    book.toc = toc

    # spine
    book.spine = ["nav", cover_chapter] + chapters

    # 네비게이션
    book.add_item(epub.EpubNcx())
    book.add_item(epub.EpubNav())

    # 출력
    os.makedirs(output_dir, exist_ok=True)
    filename = f"tech_news_{today}.epub"
    filepath = os.path.join(output_dir, filename)
    epub.write_epub(filepath, book)

    logger.info(f"EPUB 생성 완료: {filepath}")
    logger.info(f"  - 총 {len(articles)}개 기사 (KO: {ko_count}, EN: {en_count})")
    logger.info(f"  - 총 읽기 시간: 약 {total_reading}분")

    return filepath
